apiVersion: v1
kind: ConfigMap
metadata:
  name: cfs-broker
  namespace: cfs
  labels:
    k8s-app: cfs-broker
data:
  config.json: |-
    {
      "http": {
         "enabled": true,
         "listen": ":80",
         "backdoor": false
       },
      "watch_namespace": "default",
      "env": "dev"
    }