apiVersion: v1
kind: Service
metadata:
  labels:
    app: cfs-broker
  name: cfs-broker
  namespace: cfs
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: cfs-broker
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: cfs-broker
  name: cfs-broker
  namespace: cfs
spec:
  selector:
    matchLabels:
      app: cfs-broker
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cfs-broker
    spec:
      containers:
        - image: ghostbaby/cfs-broker:v0.0.2-dev
          command: [ "/app/cfs-broker" ]
          args: [ "-config","/etc/cfs-broker/config/config.json" ]
          imagePullPolicy: Always
          name: cfs-broker
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: config-volume
              mountPath: /etc/cfs-broker/config
            - mountPath: /data/kubepods
              name: kubepods
            - mountPath: /var/run
              name: docker
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsUser: 0
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Exists
      volumes:
        - name: config-volume
          configMap:
            name: cfs-broker
        - hostPath:
            path: /sys/fs/cgroup/cpu,cpuacct/kubepods.slice
            type: Directory
          name: kubepods
        - hostPath:
            path: /var/run
          name: docker