apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cfs-broker
  namespace: cfs
spec:
  endpoints:
    - interval: 30s
      port: web
  selector:
    matchLabels:
      app: cfs-broker